### ISSUE TITLE
カラーの認識について

### ISSUE THREAD

**Issue by milkyway1212** [noitaro/android-auto-play-opencv#3]
こちらのライブラリ、大変ありがたく使わせて頂いております。

今回、形は同じだけどタップすると色だけが変わる挙動
（twitterのいいねのハートマークなど）
で、タップしてもしなくても、同じ画像と認識してしまい、困っていました。

色々と試した結果、
MatchTemplateLibクラスのjudgeMatchingメソッドを呼んだ際に、
_thresholdが、0.9以上ならカラー含めて一致という判断で良いかなと思い、
AapoManagerクラスのchkImgメソッドに引数を渡して、実行しました。

しかし、メソッド内の処理にある

        # 類似度閾値超え判定
        result = self.mtl.judgeMatching()

こちらに引数を渡していない為、引数が使用できていませんでした。

chkImg2のメソッドも同様かなと思われます。

解釈が間違っていたら申し訳ありませんが、
修正などのご検討いただけると幸いです。

**Comment by noitaro** [comment]
@milkyway1212 
判断を早くするため、今は色情報を削除しています。
なので同じ形で違う色を判断するのは、現状不可能となっています。

色も含めてしまうと、認識精度が悪くなってしまうと思います。
一度検証して、使えそうなら実装しようと思います。

**Comment by milkyway1212** [comment]
@noitaro 
素早いご回答ありがとうございます。

カラーの判断が遅くなるというのは理解しました。

ただ、
judgeMatchingを呼び出した際に、thresholdというのが固定値の 0.8 のみになってしまっている。
（メソッド内では引数考慮されているが、実際の呼び出しの際には引数を渡していない）
ので、
自由に数値を使えるように、引数を渡す形にできないかなと思った次第です。
（AapoManagerクラスの５０行目など）

**Comment by noitaro** [comment]
@milkyway1212 
そうですね。
使う時と場合で変更できたら便利ですね。

修正します！
ありがとうございます。

**Comment by noitaro** [comment]
@milkyway1212 
judgeMatchingに引数で受け取ったthresholdを渡すように修正しました！
```
pip install android-auto-play-opencv==1.0.7
```

**Comment by milkyway1212** [comment]
@noitaro 
素早いご対応感謝いたします。
自分で直接修正していたのですが、新しいパソコンに入れる時に忘れるだろうなと思い、ご相談させていただきました。
しばらく使わせていただくと思います。
ありがとうございます！
